[project]
name = "sample-python-project"
version = "0.1.0"
description = "A sample Python project for doppleGanker testing."

[project.dependencies]
requests = ">=2.31.0"
flask = ">=2.0.0"
numpy = "*" 